# Generated by Django 5.0.6 on 2026-06-12 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0002_user_email_verified_user_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email_verified',
        ),
    ]
