# Generated by Django 5.0.6 on 2026-06-14 23:16

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0003_remove_user_email_verified'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('login', 'Inicio de sesion'), ('logout', 'Cierre de sesion'), ('venta', 'Venta realizada'), ('devolucion', 'Devolucion procesada'), ('producto_creado', 'Producto creado'), ('producto_editado', 'Producto editado'), ('producto_eliminado', 'Producto eliminado'), ('usuario_creado', 'Usuario creado'), ('usuario_editado', 'Usuario editado'), ('usuario_eliminado', 'Usuario eliminado')], max_length=30)),
                ('detail', models.CharField(blank=True, max_length=255)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
